import { db, writeAuditLog } from "../db/database"
import { generateAllocation, commitToHistory } from "./rotation.engine"
import { validateAllocation, validateSingleEdit, getValidHallsForStaff } from "./validation.engine"

export async function getOrCreateAllocation(
  sessionId: number,
  userIds: number[],
  hallIds: number[]
) {
  const entries = await generateAllocation(sessionId, userIds, hallIds)

  // Save to allocations table
  db.run("DELETE FROM allocations WHERE session_id = ?", [sessionId])
  for (const e of entries) {
    db.run(
      "INSERT OR REPLACE INTO allocations(session_id, user_id, hall_id, is_manually_edited, generated_hall_id) VALUES(?,?,?,0,?)",
      [sessionId, e.userId, e.hallId, e.hallId]
    )
  }
  // Update session to draft
  db.run("UPDATE exam_sessions SET status='draft' WHERE id=?", [sessionId])

  const validationEntries = entries.map(e => ({ ...e, sessionId }))
  const validation = validateAllocation(sessionId, validationEntries, hallIds, userIds)
  const fullAllocation = getSessionAllocationFull(sessionId)
  return { entries: fullAllocation, validation }
}

export function editAllocationEntry(sessionId: number, userId: number, newHallId: number, editReason?: string) {
  const current = db.query<any>("SELECT user_id, hall_id, generated_hall_id FROM allocations WHERE session_id = ?", [sessionId])
  const currentEntries = current.map((r: any) => ({ userId: r.user_id, hallId: r.hall_id, sessionId }))
  // BUG 5 fix: Extract session's declared hall pool
  const sessionHallPool = Array.from(new Set(current.map((r: any) => r.generated_hall_id || r.hall_id))) as number[]
  const error = validateSingleEdit(userId, newHallId, sessionId, currentEntries, sessionHallPool)
  if (error) return { success: false, error }

  db.run(
    "UPDATE allocations SET hall_id=?, is_manually_edited=1, edit_reason=?, updated_at=datetime('now') WHERE session_id=? AND user_id=?",
    [newHallId, editReason ?? null, sessionId, userId]
  )
  writeAuditLog(null, "EDIT_ALLOCATION", `Manual override for session ${sessionId}, user ${userId} to hall ${newHallId}`, { sessionId, userId, newHallId, editReason })
  return { success: true }
}

export async function confirmAllocation(sessionId: number) {
  const allocations = db.query<any>("SELECT * FROM allocations WHERE session_id = ?", [sessionId])
  if (!allocations.length) {
    return { success: false, error: "No allocations found for this session." }
  }
  const session = db.queryOne<any>("SELECT * FROM exam_sessions WHERE id = ?", [sessionId])
  if (!session) {
    return { success: false, error: "Exam session not found." }
  }
  const entries = allocations.map((a: any) => ({ userId: a.user_id, hallId: a.hall_id, sessionId }))
  const hallIds = allocations.map((a: any) => a.hall_id)
  const userIds = allocations.map((a: any) => a.user_id)

  const validation = validateAllocation(sessionId, entries, hallIds, userIds)
  if (!validation.isValid) return { success: false, validation }

  // BUG 4 fix: Wrap confirmation in an atomic transaction
  try {
    await db.runTransaction(async () => {
      await commitToHistory(
        sessionId,
        session.rotation_step,
        allocations.map((a: any) => ({ userId: a.user_id, hallId: a.hall_id, isAutoGenerated: !a.is_manually_edited }))
      )
      db.run("UPDATE exam_sessions SET status='confirmed', updated_at=datetime('now') WHERE id=?", [sessionId])
    })
    refreshCycleStatus(session.cycle_id)
    writeAuditLog(null, "CONFIRM_ALLOCATION", `Session ${sessionId} confirmed`, { sessionId, count: entries.length })
    return { success: true, validation }
  } catch (err: any) {
    return { success: false, error: err?.message || "Confirmation failed during transaction." }
  }
}

// A batch's status follows its sessions: "confirmed" once every session is confirmed,
// "published" once every session is published, otherwise "draft". (Publishing is no
// longer offered in the offline app, so batches normally end at "confirmed".)
export function refreshCycleStatus(cycleId: number) {
  const counts = db.queryOne<any>(
    `SELECT COUNT(*) as total,
            SUM(CASE WHEN status IN ('confirmed','published') THEN 1 ELSE 0 END) as confirmed,
            SUM(CASE WHEN status = 'published' THEN 1 ELSE 0 END) as published
     FROM exam_sessions WHERE cycle_id=?`,
    [cycleId]
  )
  const total = counts?.total ?? 0
  const status = total > 0 && counts.published === total ? "published"
    : total > 0 && counts.confirmed === total ? "confirmed"
    : "draft"
  db.run("UPDATE exam_cycles SET status=?, updated_at=datetime('now') WHERE id=?", [status, cycleId])
}

export function publishAllocation(sessionId: number) {
  const session = db.queryOne<any>("SELECT * FROM exam_sessions WHERE id = ?", [sessionId])
  if (!session) return { success: false, error: "Session not found." }
  if (session.status !== "confirmed") return { success: false, error: "Allocation must be confirmed before publishing." }
  db.run("UPDATE exam_sessions SET status='published', updated_at=datetime('now') WHERE id=?", [sessionId])
  // Roll up cycle status: if all sessions in cycle are published, mark cycle as published
  const unpublished = db.queryOne<any>(
    "SELECT COUNT(*) as c FROM exam_sessions WHERE cycle_id=? AND status != 'published'",
    [session.cycle_id]
  )
  if (!unpublished || unpublished.c === 0) {
    db.run("UPDATE exam_cycles SET status='published' WHERE id=?", [session.cycle_id])
  }
  writeAuditLog(null, "PUBLISH_ALLOCATION", `Session ${sessionId} published`, { sessionId })

  // In-app notifications for assigned staff
  try {
    const allocations = db.query<any>(
      `SELECT a.user_id, h.hall_code, ec.name as cycle_name
       FROM allocations a
       JOIN halls h ON a.hall_id = h.id
       JOIN exam_sessions es ON a.session_id = es.id
       JOIN exam_cycles ec ON es.cycle_id = ec.id
       WHERE a.session_id = ?`,
      [sessionId]
    )
    const sessionLabel = `${session.exam_date} ${session.session_type}`
    for (const a of allocations) {
      db.run(
        "INSERT INTO notifications(user_id, title, message, session_id) VALUES(?,?,?,?)",
        [
          a.user_id,
          "New Exam Duty Published",
          `Your invigilation duty has been published for ${sessionLabel} — Hall ${a.hall_code} (${a.cycle_name}).`,
          sessionId
        ]
      )
    }
  } catch (e) {
    console.warn("[HIAS] Failed to create notifications in desktop:", e)
  }

  return { success: true }
}


export function getSessionAllocationFull(sessionId: number) {
  return db.query(
    `SELECT a.id, a.is_manually_edited, a.edit_reason,
            u.id as userId, u.staff_id, u.name as userName, u.designation,
            d.name as deptName, d.code as deptCode,
            h.id as hallId, h.hall_code, h.name as hallName, h.block as hallBlock, h.floor as hallFloor,
            gh.hall_code as generatedHallCode
     FROM allocations a
     JOIN users u ON a.user_id = u.id
     JOIN halls h ON a.hall_id = h.id
     LEFT JOIN departments d ON u.department_id = d.id
     LEFT JOIN halls gh ON a.generated_hall_id = gh.id
     WHERE a.session_id = ?
     ORDER BY d.code, u.name`,
    [sessionId]
  )
}

export function getValidHallsFor(userId: number, sessionId: number) {
  const occupied = db.query<any>("SELECT hall_id FROM allocations WHERE session_id = ?", [sessionId]).map((r: any) => r.hall_id)
  // BUG 5 fix: Session hall pool only
  const poolRows = db.query<any>(
    `SELECT DISTINCT h.id, h.sort_order 
     FROM allocations a
     JOIN halls h ON h.id = COALESCE(a.generated_hall_id, a.hall_id)
     WHERE a.session_id = ?
     ORDER BY h.sort_order, h.id`,
    [sessionId]
  )
  let sessionHalls = poolRows.map((r: any) => r.id)
  if (sessionHalls.length === 0) {
    sessionHalls = db.query<any>("SELECT id FROM halls WHERE is_active = 1 ORDER BY sort_order, id").map((h: any) => h.id)
  }
  return getValidHallsForStaff(userId, sessionId, sessionHalls, occupied)
}

export function getStaffDutyHistory(userId: number) {
  return db.query(
    `SELECT es.exam_date, es.session_type, es.reporting_time, es.exam_start, es.exam_end,
            h.id as hallId, h.hall_code, h.name as hallName, h.block as hallBlock, h.floor as hallFloor,
            ec.name as cycleName, ec.academic_year,
            a.is_manually_edited
     FROM allocations a
     JOIN exam_sessions es ON a.session_id = es.id
     JOIN halls h ON a.hall_id = h.id
     JOIN exam_cycles ec ON es.cycle_id = ec.id
     WHERE a.user_id = ? AND es.status IN ('confirmed','published')
     ORDER BY es.exam_date DESC, es.session_type ASC`,
    [userId]
  )
}

export function restartRotation() {
  db.run("DELETE FROM rotation_history")
  const activeStaff = db.query<any>("SELECT id FROM users WHERE role = 'staff' AND is_active = 1")
  for (const staff of activeStaff) {
    db.run(
      "INSERT INTO notifications (user_id, title, message, is_read, created_at) VALUES (?, ?, ?, 0, datetime('now'))",
      [
        staff.id,
        "Rotation Restarted",
        "Your entire hall rotation history has been restarted by the admin. Your rotation cycle has been reset, so every hall is open to you again from your next duty."
      ]
    )
  }
  writeAuditLog(null, "ROTATION_RESTART", "Entire rotation history restarted by admin", { affectedStaffCount: activeStaff.length })
  return { success: true }
}

export function getNotifications(userId: number) {
  return db.query("SELECT * FROM notifications WHERE user_id = ? ORDER BY id DESC", [userId])
}

export function getUnreadCount(userId: number) {
  const row = db.queryOne<any>("SELECT COUNT(*) as cnt FROM notifications WHERE user_id = ? AND is_read = 0", [userId])
  return row?.cnt || 0
}

export function markNotificationRead(id: number) {
  db.run("UPDATE notifications SET is_read = 1 WHERE id = ?", [id])
  return { success: true }
}

export function markAllRead(userId: number) {
  db.run("UPDATE notifications SET is_read = 1 WHERE user_id = ?", [userId])
  return { success: true }
}

export function hardDeleteUser(id: number) {
  const inHistory = db.queryOne<any>("SELECT id FROM rotation_history WHERE user_id = ? LIMIT 1", [id])
  const inAllocations = db.queryOne<any>("SELECT id FROM allocations WHERE user_id = ? LIMIT 1", [id])
  if (inHistory || inAllocations) {
    return { success: false, error: "Cannot permanently delete: this staff member has allocation history." }
  }
  const user = db.queryOne<any>("SELECT staff_id, name FROM users WHERE id = ?", [id])
  db.run("DELETE FROM users WHERE id = ?", [id])
  writeAuditLog(null, "STAFF_HARD_DELETE", `Staff permanently deleted: ${user?.staff_id ?? id} - ${user?.name ?? ""}`, { id, staff_id: user?.staff_id })
  return { success: true }
}

export function deleteSession(id: number) {
  const session = db.queryOne<any>("SELECT * FROM exam_sessions WHERE id=?", [id])
  if (!session) return { success: false, error: "Session not found." }
  if (session.status === "confirmed" || session.status === "published") {
    return { success: false, error: "Cannot delete a confirmed or published session." }
  }
  db.run("DELETE FROM allocations WHERE session_id=?", [id])
  db.run("DELETE FROM exam_sessions WHERE id=?", [id])
  // Renumber remaining sessions in this cycle to maintain contiguous 1..N rotation_step
  const remaining = db.query<any>("SELECT id FROM exam_sessions WHERE cycle_id=? ORDER BY rotation_step, id", [session.cycle_id])
  remaining.forEach((s, idx) => {
    db.run("UPDATE exam_sessions SET rotation_step=? WHERE id=?", [idx + 1, s.id])
  })
  refreshCycleStatus(session.cycle_id)
  return { success: true }
}

// Deleting an entire batch (exam cycle) is a deliberate, explicit action distinct from
// deleteSession above: unlike removing one session from an in-progress workflow, this is
// meant to work even on a confirmed/published batch (the UI gates it behind a password
// re-confirmation instead). It removes the batch's rotation_history too, so any fairness
// effect that batch had on future allocations is fully undone along with it — the rotation
// engine only ever reads the *latest* remaining entry per staff member and the running
// MAX(global_order), neither of which requires the deleted step numbers to be contiguous.
export function deleteCycle(id: number) {
  const cycle = db.queryOne<any>("SELECT * FROM exam_cycles WHERE id=?", [id])
  if (!cycle) return { success: false, error: "Allocation batch not found." }

  return db.runTransaction(() => {
    const sessions = db.query<any>("SELECT id FROM exam_sessions WHERE cycle_id=?", [id])
    for (const s of sessions) {
      db.run("DELETE FROM rotation_history WHERE session_id=?", [s.id])
      db.run("DELETE FROM allocations WHERE session_id=?", [s.id])
    }
    db.run("DELETE FROM exam_sessions WHERE cycle_id=?", [id])
    db.run("DELETE FROM exam_cycles WHERE id=?", [id])
    writeAuditLog(null, "CYCLE_DELETE",
      `Allocation batch deleted: ${cycle.name} (${cycle.academic_year}) — ${sessions.length} session(s) removed`,
      { id, name: cycle.name, sessionCount: sessions.length })
    return { success: true }
  })
}