/**
 * ROTATION ENGINE
 * Hall allocation: seeded random draw within each person's rotation cycle (see shared/assignment.ts).
 * Edit-aware: if admin edited a session, that becomes the rotation baseline.
 * Individual-aware: each staff member maintains their own rotation state.
 */
import { db } from "../db/database"
import { assignHalls, minimumRepeats, visitedThisCycle, allocationSeed, type AssignmentResult } from "../../shared/assignment"

export interface AllocationEntry {
  userId: number
  hallId: number
  isAutoGenerated: boolean
}

export async function generateAllocation(
  sessionId: number,
  userIds: number[],
  hallIds: number[]
): Promise<AllocationEntry[]> {
  if (userIds.length !== hallIds.length) {
    throw new Error(`Staff count (${userIds.length}) must equal hall count (${hallIds.length})`)
  }
  const session = db.queryOne<any>("SELECT cycle_id, created_at FROM exam_sessions WHERE id = ?", [sessionId])
  const seed = allocationSeed({ cycleId: session?.cycle_id, sessionId, createdAt: session?.created_at, userIds, hallIds })
  return assignOptimally(userIds, hallIds, seed).entries
}

// ─── 1:1 allocation: optimal assignment (see assignment.ts) ─────────────────

/** A staff member's confirmed halls, most recent first. */
export function hallHistory(userId: number): number[] {
  return db.query<any>(
    "SELECT hall_id FROM rotation_history WHERE user_id = ? ORDER BY COALESCE(global_order, 0) DESC, datetime(recorded_at) DESC, id DESC",
    [userId]
  ).map((r: any) => r.hall_id)
}

export function assignOptimally(userIds: number[], hallIds: number[], seed = ""): AssignmentResult {
  return assignHalls(userIds, hallIds, hallHistory, seed)
}

/** Halls of `pool` this staff member has already had in their current rotation cycle (R1). */
export function hallsVisitedThisCycle(userId: number, pool: number[]): Set<number> {
  return visitedThisCycle(hallHistory(userId), pool)
}

/** Minimum number of R1 repeats any assignment of these staff to these halls must contain. */
export function minimumUnavoidableRepeats(userIds: number[], hallIds: number[]): number {
  return minimumRepeats(userIds, hallIds, hallHistory)
}

export async function commitToHistory(
  sessionId: number,
  rotationStep: number,
  entries: AllocationEntry[]
): Promise<void> {
  const maxRow = db.queryOne<{ max_order: number | null }>(
    "SELECT MAX(global_order) as max_order FROM rotation_history"
  )
  let nextGlobalOrder = (maxRow?.max_order ?? 0) + 1

  for (const e of entries) {
    const existing = db.queryOne<{ id: number; global_order: number }>(
      "SELECT id, global_order FROM rotation_history WHERE user_id = ? AND session_id = ?",
      [e.userId, sessionId]
    )

    if (existing) {
      db.run(
        `UPDATE rotation_history
         SET hall_id = ?, rotation_step = ?, recorded_at = datetime('now')
         WHERE id = ?`,
        [e.hallId, rotationStep, existing.id]
      )
    } else {
      db.run(
        `INSERT INTO rotation_history(user_id, session_id, hall_id, rotation_step, global_order, recorded_at)
         VALUES(?,?,?,?,?,datetime('now'))`,
        [e.userId, sessionId, e.hallId, rotationStep, nextGlobalOrder++]
      )
    }
  }
}

export function getStaffHallHistory(userId: number): any[] {
  return db.query(
    `SELECT rh.hall_id as hallId, rh.session_id as sessionId, rh.rotation_step as rotationStep,
            rh.global_order as globalOrder, es.exam_date as examDate, es.session_type as sessionType
     FROM rotation_history rh
     JOIN exam_sessions es ON rh.session_id = es.id
     WHERE rh.user_id = ?
     ORDER BY COALESCE(rh.global_order, 0) ASC, datetime(rh.recorded_at) ASC, rh.id ASC`,
    [userId]
  )
}
