/**
 * The printable duty slip (Staff Duty page, web build). It is rendered with React, like the
 * rest of the interface, so every value (staff name, batch, hall, college name) is HTML-escaped:
 * a name such as O'Brien, "A & B" or one containing "<" is shown as text and can never become
 * markup in the print window.
 */
import { renderToStaticMarkup } from "react-dom/server"
import { formatDate, formatSession, formatTime12h, hallLocation } from "./utils"
import type { StaffDutyRow } from "../../../shared/staff-duty"

// Fixed styling only; no data is ever placed in it.
const STYLE = `
  body { font-family: Arial, sans-serif; margin: 40px; color: #111; }
  h1 { text-align: center; font-size: 16px; margin: 0; }
  .divider { border-top: 2px solid #222; margin: 10px 0; }
  .title { font-size: 14px; font-weight: bold; text-align: center; margin: 12px 0 20px; letter-spacing: 1px; text-transform: uppercase; }
  table { width: 100%; border-collapse: collapse; margin: 10px 0; }
  td { padding: 10px 12px; border: 1px solid #ccc; font-size: 13px; }
  td:first-child { font-weight: bold; width: 35%; background: #f9f9f9; }
  .hall-box { font-size: 28px; font-weight: 900; text-align: center; border: 3px solid #333; padding: 10px; margin: 20px auto; width: 200px; letter-spacing: 2px; }
  .location { text-align: center; font-size: 12px; color: #555; }
  .none { text-align: center; color: #888; }
  .footer { margin-top: 30px; font-size: 11px; color: #888; text-align: center; }
  .sig { margin-top: 50px; display: flex; justify-content: space-between; font-size: 12px; }
  @media print { body { margin: 20px; } }
`

export interface DutySlipInput {
  collegeName: string
  shortName: string
  staffName?: string
  staffId?: string
  duty: StaffDutyRow | null
  generatedAt: string
}

/** The complete HTML document of the slip. */
export function dutySlipHtml({ collegeName, shortName, staffName, staffId, duty, generatedAt }: DutySlipInput): string {
  const head = renderToStaticMarkup(<title>{`Duty Slip — HIAS ${shortName}`}</title>)
  const body = renderToStaticMarkup(
    <>
      <h1>{collegeName}</h1>
      <div className="divider" />
      <div className="title">Invigilation Duty Slip</div>
      {duty ? (
        <>
          <table>
            <tbody>
              <tr><td>Staff Name</td><td>{staffName}</td></tr>
              <tr><td>Staff ID</td><td>{staffId}</td></tr>
              <tr><td>Exam Date</td><td>{formatDate(duty.exam_date)}</td></tr>
              <tr><td>Session</td><td>{formatSession(duty.session_type)}</td></tr>
              <tr><td>Reporting Time</td><td>{formatTime12h(duty.reporting_time)}</td></tr>
              <tr><td>Exam Time</td><td>{formatTime12h(duty.exam_start)} – {formatTime12h(duty.exam_end)}</td></tr>
              <tr><td>Allocation Batch</td><td>{duty.cycleName}</td></tr>
            </tbody>
          </table>
          <div className="hall-box">{duty.hall_code}</div>
          <p className="location">{hallLocation({ block: duty.hallBlock, floor: duty.hallFloor })}</p>
        </>
      ) : (
        <p className="none">No upcoming duty assigned.</p>
      )}
      <div className="sig">
        <div>Signature of Invigilator</div>
        <div>Controller of Examinations</div>
      </div>
      <div className="footer">Generated by HIAS — {shortName} — {generatedAt}</div>
    </>
  )
  return `<!DOCTYPE html><html><head><meta charset="utf-8">${head}<style>${STYLE}</style></head><body>${body}</body></html>`
}
