import { useEffect, useState } from "react"
import { Calendar, Clock, MapPin, Building2, Printer, ChevronRight, Bell } from "lucide-react"
import { api } from "../lib/api"
import { useAuthStore } from "../store/auth.store"
import { formatDate, formatSession } from "../lib/utils"

export default function StaffDutyPage() {
  const { user } = useAuthStore()
  const [duties, setDuties] = useState<any[]>([])
  const [settings, setSettings] = useState<Record<string, string>>({})
  const [unreadNotifications, setUnreadNotifications] = useState<any[]>([])

  useEffect(() => {
    if (user) {
      api.getStaffDutyHistory(user.id).then(setDuties)
      api.getNotifications(user.id).then(notes => setUnreadNotifications(notes.filter((n: any) => !n.is_read)))
    }
    api.getSettings().then(setSettings)
  }, [user])

  const today = new Date().toISOString().split("T")[0]
  const upcoming = duties.filter(d => d.exam_date >= today)
  const past = duties.filter(d => d.exam_date < today)
  const next = upcoming[0]

  function printDutySlip() {
    const win = window.open("", "_blank", "width=800,height=600")
    if (!win) return
    win.document.write(`
      <html><head><title>Duty Slip — EIAS SXCCE</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #111; }
        h1 { text-align: center; font-size: 16px; margin: 0; }
        h2 { text-align: center; font-size: 13px; margin: 4px 0 20px; color: #555; font-weight: normal; }
        .divider { border-top: 2px solid #222; margin: 10px 0; }
        .title { font-size: 14px; font-weight: bold; text-align: center; margin: 12px 0 20px; letter-spacing: 1px; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        td { padding: 10px 12px; border: 1px solid #ccc; font-size: 13px; }
        td:first-child { font-weight: bold; width: 35%; background: #f9f9f9; }
        .hall-box { font-size: 28px; font-weight: 900; text-align: center; border: 3px solid #333; padding: 10px; margin: 20px auto; width: 200px; letter-spacing: 2px; }
        .footer { margin-top: 30px; font-size: 11px; color: #888; text-align: center; }
        .sig { margin-top: 50px; display: flex; justify-content: space-between; font-size: 12px; }
        @media print { body { margin: 20px; } }
      </style></head><body>
      <h1>${settings["college.name"] ?? "St. Xavier's Catholic College of Engineering (Autonomous), Nagercoil"}</h1>
      <div class="divider"></div>
      <div class="title">Invigilation Duty Slip</div>
      ${next ? `
      <table>
        <tr><td>Staff Name</td><td>${user?.name}</td></tr>
        <tr><td>Staff ID</td><td>${user?.staff_id}</td></tr>
        <tr><td>Exam Date</td><td>${formatDate(next.exam_date)}</td></tr>
        <tr><td>Session</td><td>${formatSession(next.session_type)}</td></tr>
        <tr><td>Reporting Time</td><td>${next.reporting_time}</td></tr>
        <tr><td>Exam Time</td><td>${next.exam_start} – ${next.exam_end}</td></tr>
        <tr><td>Exam Cycle</td><td>${next.cycleName}</td></tr>
      </table>
      <div class="hall-box">${next.hall_code}</div>
      <p style="text-align:center; font-size:12px; color:#555;">${next.hallName}</p>
      ` : `<p style="text-align:center; color:#888;">No upcoming duty assigned.</p>`}
      <div class="sig">
        <div>Signature of Invigilator</div>
        <div>Controller of Examinations</div>
      </div>
      <div class="footer">Generated by EIAS &mdash; ${settings["college.short_name"] ?? "SXCCE"} &mdash; ${new Date().toLocaleString()}</div>
      </body></html>
    `)
    win.document.close()
    win.focus()
    setTimeout(() => win.print(), 500)
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-brand-textmain">My Invigilation Duty</h1>
        {next && (
          <button onClick={printDutySlip}
            className="btn-secondary flex items-center gap-2">
            <Printer className="w-4 h-4" /> Print Duty Slip
          </button>
        )}
      </div>

      {unreadNotifications.length > 0 && (
        <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 flex items-start justify-between gap-3 animate-in fade-in">
          <div className="flex items-start gap-3">
            <Bell className="w-5 h-5 text-brand-primary flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-semibold text-blue-900">New Exam Duty Assignment</p>
              <p className="text-xs text-blue-800 mt-0.5">{unreadNotifications[0].message}</p>
            </div>
          </div>
          <button
            onClick={async () => {
              if (user) await api.markAllNotificationsRead(user.id)
              setUnreadNotifications([])
            }}
            className="text-xs bg-brand-primary text-white px-3 py-1.5 rounded-lg hover:bg-brand-primary/90 font-medium whitespace-nowrap"
          >
            Acknowledge
          </button>
        </div>
      )}

      {/* Next upcoming duty */}
      {next ? (
        <div className="bg-brand-sidebar rounded-2xl p-6 text-white shadow-xl">
          <div className="mb-1">
            <p className="text-brand-light text-xs font-semibold uppercase tracking-wider">Next Upcoming Duty</p>
            <p className="text-gray-400 text-xs mt-0.5">{next.cycleName}</p>
          </div>
          <div className="grid grid-cols-2 gap-5 mt-5">
            <div className="flex items-start gap-3">
              <Calendar className="w-5 h-5 text-brand-light mt-0.5 flex-shrink-0" />
              <div><p className="text-xs text-gray-400">Exam Date</p><p className="text-lg font-bold">{formatDate(next.exam_date)}</p></div>
            </div>
            <div className="flex items-start gap-3">
              <Clock className="w-5 h-5 text-brand-light mt-0.5 flex-shrink-0" />
              <div>
                <p className="text-xs text-gray-400">Session</p>
                <p className="text-lg font-bold">{formatSession(next.session_type)}</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <MapPin className="w-5 h-5 text-brand-light mt-0.5 flex-shrink-0" />
              <div>
                <p className="text-xs text-gray-400">Hall</p>
                <p className="text-3xl font-black text-brand-light tracking-wide">{next.hall_code}</p>
                <p className="text-xs text-gray-400 mt-0.5">{next.hallName}</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <Clock className="w-5 h-5 text-brand-light mt-0.5 flex-shrink-0" />
              <div>
                <p className="text-xs text-gray-400">Reporting Time</p>
                <p className="font-bold text-lg">{next.reporting_time}</p>
                <p className="text-xs text-gray-400 mt-1">Exam Duration</p>
                <p className="font-medium text-sm">{next.exam_start} – {next.exam_end}</p>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="card text-center py-12 text-brand-textsec">
          <Building2 className="w-10 h-10 mx-auto mb-3 opacity-30" />
          <p className="font-medium">No upcoming duty assigned</p>
          <p className="text-sm mt-1">Your next duty slip will appear here once published by the admin.</p>
        </div>
      )}

      {/* Upcoming (rest) */}
      {upcoming.length > 1 && (
        <div className="card">
          <h2 className="text-sm font-semibold text-brand-textmain mb-3">Upcoming Duties ({upcoming.length - 1} more)</h2>
          <div className="space-y-2">
            {upcoming.slice(1).map((d: any, i: number) => (
              <div key={i} className="flex items-center justify-between p-3 rounded-lg bg-brand-verylight border border-brand-light">
                <div className="flex items-center gap-3">
                  <Calendar className="w-4 h-4 text-brand-primary" />
                  <div>
                    <p className="text-sm font-medium">{formatDate(d.exam_date)} · {d.session_type}</p>
                    <p className="text-xs text-brand-textsec">{d.cycleName}</p>
                  </div>
                </div>
                <span className="font-bold text-brand-primary bg-white px-3 py-1 rounded-lg border border-brand-light text-sm">
                  {d.hall_code}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Past duties */}
      {past.length > 0 && (
        <div className="card">
          <h2 className="text-sm font-semibold text-brand-textmain mb-3">Past Duties</h2>
          <table className="w-full text-sm">
            <thead>
              <tr>{["Date","Session","Hall","Reporting","Exam Time","Cycle"].map(h =>
                <th key={h} className="text-left py-2 text-xs font-semibold text-brand-textsec uppercase tracking-wider pr-4">{h}</th>)}</tr>
            </thead>
            <tbody className="divide-y divide-brand-border">
              {past.map((d: any, i: number) => (
                <tr key={i} className="hover:bg-gray-50">
                  <td className="py-2.5 pr-4 font-medium">{formatDate(d.exam_date)}</td>
                  <td className="py-2.5 pr-4">{d.session_type}</td>
                  <td className="py-2.5 pr-4 font-bold text-brand-primary">{d.hall_code}</td>
                  <td className="py-2.5 pr-4 text-brand-textsec">{d.reporting_time}</td>
                  <td className="py-2.5 pr-4 text-brand-textsec">{d.exam_start} – {d.exam_end}</td>
                  <td className="py-2.5 text-brand-textsec text-xs">{d.cycleName}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
