/**
 * HALL ASSIGNMENT (pure logic, no database access)
 * Shared by the desktop engine (rotation.engine.ts) and the web build (web-api.ts),
 * which each supply the staff members' hall histories.
 *
 * Assigning halls one staff member at a time ("next hall after your last one; if
 * taken, keep going round") breaks down as soon as the staff on duty change from
 * session to session (more staff than halls, the normal case): two people want the
 * same next hall and the loser is pushed into a hall they had recently, which R1
 * then rejects. Instead, all staff of the session are assigned together by solving
 * a minimum-cost perfect matching (Hungarian algorithm) over this cost:
 *
 *   R1_PENALTY + recency   if the hall is among the person's last (n - 1) halls (R1),
 *                          more for more recent visits
 * + visits * (n + 1)       how often they have already had this hall (least-used first)
 * + distance               circular steps from their last hall (their natural "next")
 *
 * R1_PENALTY dominates, so R1 is never broken when any valid assignment exists, and
 * the number of unavoidable repeats is minimal when none does (then the repeated hall
 * is the one visited longest ago). With a fixed team the cheapest choice is always
 * "+1", which is the classic perfect rotation.
 */

export interface HallAssignment {
  userId: number
  hallId: number
  isAutoGenerated: boolean
}

export interface AssignmentResult {
  entries: HallAssignment[]
  /** Number of R1 repeats in the result; > 0 only when no R1-valid assignment exists. */
  unavoidableRepeats: number
}

/** A staff member's confirmed halls, most recent first. */
export type HallHistory = (userId: number) => number[]

// Must exceed the largest possible sum of all other costs in a session (recency,
// visits and distance for every person), so one extra repeat is never traded for them.
const R1_PENALTY = 1_000_000_000
// Among unavoidable repeats, prefer the hall visited longest ago.
const RECENCY_PENALTY = 1_000

export function assignHalls(userIds: number[], hallIds: number[], historyOf: HallHistory): AssignmentResult {
  if (userIds.length !== hallIds.length) {
    throw new Error(`Staff count (${userIds.length}) must equal hall count (${hallIds.length})`)
  }
  const n = hallIds.length
  if (n === 0) return { entries: [], unavoidableRepeats: 0 }

  const cost: number[][] = userIds.map(userId => {
    const history = historyOf(userId)
    const recent = history.slice(0, Math.max(0, n - 1))
    const visits = new Map<number, number>()
    for (const h of history) visits.set(h, (visits.get(h) ?? 0) + 1)
    const lastIndex = history.length ? hallIds.indexOf(history[0]) : -1
    return hallIds.map((hallId, j) => {
      // Staff new to this pool start from the first hall onwards.
      const distance = lastIndex === -1 ? j : ((j - lastIndex + n) % n || n)
      const age = recent.indexOf(hallId) // 0 = their very last hall
      const r1 = age === -1 ? 0 : R1_PENALTY + (recent.length - age) * RECENCY_PENALTY
      return r1 + (visits.get(hallId) ?? 0) * (n + 1) + distance
    })
  })

  const match = hungarian(cost)
  let unavoidableRepeats = 0
  const entries = userIds.map((userId, i) => {
    if (cost[i][match[i]] >= R1_PENALTY) unavoidableRepeats++
    return { userId, hallId: hallIds[match[i]], isAutoGenerated: true }
  })
  return { entries, unavoidableRepeats }
}

/** Minimum number of R1 repeats any assignment of these staff to these halls must contain. */
export function minimumRepeats(userIds: number[], hallIds: number[], historyOf: HallHistory): number {
  if (userIds.length !== hallIds.length || userIds.length === 0) return 0
  return assignHalls(userIds, hallIds, historyOf).unavoidableRepeats
}

/**
 * Minimum-cost perfect matching on a square cost matrix (Hungarian algorithm with
 * potentials, O(n^3)). Returns, for each row, the column assigned to it.
 */
function hungarian(cost: number[][]): number[] {
  const n = cost.length
  const u = new Array(n + 1).fill(0), v = new Array(n + 1).fill(0)
  const p = new Array(n + 1).fill(0), way = new Array(n + 1).fill(0)
  for (let i = 1; i <= n; i++) {
    p[0] = i
    let j0 = 0
    const minv = new Array(n + 1).fill(Infinity)
    const used = new Array(n + 1).fill(false)
    do {
      used[j0] = true
      const i0 = p[j0]
      let delta = Infinity, j1 = 0
      for (let j = 1; j <= n; j++) {
        if (used[j]) continue
        const cur = cost[i0 - 1][j - 1] - u[i0] - v[j]
        if (cur < minv[j]) { minv[j] = cur; way[j] = j0 }
        if (minv[j] < delta) { delta = minv[j]; j1 = j }
      }
      for (let j = 0; j <= n; j++) {
        if (used[j]) { u[p[j]] += delta; v[j] -= delta } else minv[j] -= delta
      }
      j0 = j1
    } while (p[j0] !== 0)
    do { const j1 = way[j0]; p[j0] = p[j1]; j0 = j1 } while (j0)
  }
  const result = new Array(n)
  for (let j = 1; j <= n; j++) result[p[j] - 1] = j - 1
  return result
}
