import { db } from "../db/database"
import { generateAllocation, generateFirstAllocation, commitToHistory } from "./rotation.engine"
import { validateAllocation, validateSingleEdit, getValidHallsForStaff } from "./validation.engine"

export async function getOrCreateAllocation(sessionId: number, userIds: number[], hallIds: number[]) {
  const histCount = db.queryOne<any>("SELECT COUNT(*) as c FROM rotation_history")
  const isFirst = (histCount?.c ?? 0) === 0

  const entries = isFirst
    ? generateFirstAllocation(userIds, hallIds)
    : await generateAllocation(sessionId, userIds, hallIds)

  // Save to allocations table
  db.run("DELETE FROM allocations WHERE session_id = ?", [sessionId])
  for (const e of entries) {
    db.run(
      "INSERT OR REPLACE INTO allocations(session_id, user_id, hall_id, is_manually_edited, generated_hall_id) VALUES(?,?,?,0,?)",
      [sessionId, e.userId, e.hallId, e.hallId]
    )
  }
  // Update session to draft
  db.run("UPDATE exam_sessions SET status='draft' WHERE id=?", [sessionId])

  const validationEntries = entries.map(e => ({ ...e, sessionId }))
  const validation = validateAllocation(sessionId, validationEntries, hallIds, userIds)
  const fullAllocation = getSessionAllocationFull(sessionId)
  return { entries: fullAllocation, validation }
}

export function editAllocationEntry(sessionId: number, userId: number, newHallId: number, editReason?: string) {
  const current = db.query<any>("SELECT user_id, hall_id FROM allocations WHERE session_id = ?", [sessionId])
  const currentEntries = current.map((r: any) => ({ userId: r.user_id, hallId: r.hall_id, sessionId }))
  const error = validateSingleEdit(userId, newHallId, sessionId, currentEntries)
  if (error) return { success: false, error }

  db.run(
    "UPDATE allocations SET hall_id=?, is_manually_edited=1, edit_reason=?, updated_at=datetime('now') WHERE session_id=? AND user_id=?",
    [newHallId, editReason ?? null, sessionId, userId]
  )
  return { success: true }
}

export async function confirmAllocation(sessionId: number) {
  const allocations = db.query<any>("SELECT * FROM allocations WHERE session_id = ?", [sessionId])
  const session = db.queryOne<any>("SELECT * FROM exam_sessions WHERE id = ?", [sessionId])
  const entries = allocations.map((a: any) => ({ userId: a.user_id, hallId: a.hall_id, sessionId }))
  const hallIds = allocations.map((a: any) => a.hall_id)
  const userIds = allocations.map((a: any) => a.user_id)

  const validation = validateAllocation(sessionId, entries, hallIds, userIds)
  if (!validation.isValid) return { success: false, validation }

  await commitToHistory(
    sessionId,
    session.rotation_step,
    allocations.map((a: any) => ({ userId: a.user_id, hallId: a.hall_id, isAutoGenerated: !a.is_manually_edited }))
  )
  db.run("UPDATE exam_sessions SET status='confirmed', updated_at=datetime('now') WHERE id=?", [sessionId])
  return { success: true, validation }
}

export function publishAllocation(sessionId: number) {
  const session = db.queryOne<any>("SELECT status FROM exam_sessions WHERE id = ?", [sessionId])
  if (session?.status !== "confirmed") return { success: false, error: "Allocation must be confirmed before publishing." }
  db.run("UPDATE exam_sessions SET status='published', updated_at=datetime('now') WHERE id=?", [sessionId])
  return { success: true }
}

export function getSessionAllocationFull(sessionId: number) {
  return db.query(
    `SELECT a.id, a.is_manually_edited, a.edit_reason,
            u.id as userId, u.staff_id, u.name as userName, u.designation,
            d.name as deptName, d.code as deptCode,
            h.id as hallId, h.hall_code, h.name as hallName,
            gh.hall_code as generatedHallCode
     FROM allocations a
     JOIN users u ON a.user_id = u.id
     JOIN halls h ON a.hall_id = h.id
     LEFT JOIN departments d ON u.department_id = d.id
     LEFT JOIN halls gh ON a.generated_hall_id = gh.id
     WHERE a.session_id = ?
     ORDER BY d.code, u.name`,
    [sessionId]
  )
}

export function getValidHallsFor(userId: number, sessionId: number) {
  const occupied = db.query<any>("SELECT hall_id FROM allocations WHERE session_id = ?", [sessionId]).map((r: any) => r.hall_id)
  const allHalls = db.query<any>("SELECT id FROM halls WHERE is_active = 1 ORDER BY sort_order").map((h: any) => h.id)
  return getValidHallsForStaff(userId, sessionId, allHalls, occupied)
}

export function getStaffDutyHistory(userId: number) {
  return db.query(
    `SELECT es.exam_date, es.session_type, es.reporting_time, es.exam_start, es.exam_end,
            h.hall_code, h.name as hallName,
            ec.name as cycleName, ec.academic_year,
            a.is_manually_edited
     FROM allocations a
     JOIN exam_sessions es ON a.session_id = es.id
     JOIN halls h ON a.hall_id = h.id
     JOIN exam_cycles ec ON es.cycle_id = ec.id
     WHERE a.user_id = ? AND es.status = 'published'
     ORDER BY es.exam_date DESC, es.session_type ASC`,
    [userId]
  )
}
