import { db, writeAuditLog } from "../db/database"
import { generateAllocation, commitToHistory } from "./rotation.engine"
import { validateAllocation, validateSingleEdit, getValidHallsForStaff } from "./validation.engine"

export async function getOrCreateAllocation(
  sessionId: number,
  userIds: number[],
  hallIds: number[],
  hallCapacities?: Map<number, number>
) {
  // Build hall requirements if capacities provided
  let hallRequirements: Map<number, number> | undefined
  if (hallCapacities && hallCapacities.size > 0) {
    hallRequirements = new Map()
    for (const hallId of hallIds) {
      const capacity = hallCapacities.get(hallId) || 30
      hallRequirements.set(hallId, Math.max(1, Math.ceil(capacity / 30)))
    }
  }

  const entries = await generateAllocation(sessionId, userIds, hallIds, hallCapacities)

  // Save to allocations table
  db.run("DELETE FROM allocations WHERE session_id = ?", [sessionId])
  for (const e of entries) {
    db.run(
      "INSERT OR REPLACE INTO allocations(session_id, user_id, hall_id, is_manually_edited, generated_hall_id) VALUES(?,?,?,0,?)",
      [sessionId, e.userId, e.hallId, e.hallId]
    )
  }
  // Update session to draft
  db.run("UPDATE exam_sessions SET status='draft' WHERE id=?", [sessionId])

  const validationEntries = entries.map(e => ({ ...e, sessionId }))
  const validation = validateAllocation(sessionId, validationEntries, hallIds, userIds, hallRequirements)
  const fullAllocation = getSessionAllocationFull(sessionId)
  return { entries: fullAllocation, validation }
}

export function editAllocationEntry(sessionId: number, userId: number, newHallId: number, editReason?: string) {
  const current = db.query<any>("SELECT user_id, hall_id, generated_hall_id FROM allocations WHERE session_id = ?", [sessionId])
  const currentEntries = current.map((r: any) => ({ userId: r.user_id, hallId: r.hall_id, sessionId }))
  // BUG 5 fix: Extract session's declared hall pool
  const sessionHallPool = Array.from(new Set(current.map((r: any) => r.generated_hall_id || r.hall_id))) as number[]
  const error = validateSingleEdit(userId, newHallId, sessionId, currentEntries, sessionHallPool)
  if (error) return { success: false, error }

  db.run(
    "UPDATE allocations SET hall_id=?, is_manually_edited=1, edit_reason=?, updated_at=datetime('now') WHERE session_id=? AND user_id=?",
    [newHallId, editReason ?? null, sessionId, userId]
  )
  writeAuditLog(null, "EDIT_ALLOCATION", `Manual override for session ${sessionId}, user ${userId} to hall ${newHallId}`, { sessionId, userId, newHallId, editReason })
  return { success: true }
}

export async function confirmAllocation(sessionId: number) {
  const allocations = db.query<any>("SELECT * FROM allocations WHERE session_id = ?", [sessionId])
  if (!allocations.length) {
    return { success: false, error: "No allocations found for this session." }
  }
  const session = db.queryOne<any>("SELECT * FROM exam_sessions WHERE id = ?", [sessionId])
  if (!session) {
    return { success: false, error: "Exam session not found." }
  }
  const entries = allocations.map((a: any) => ({ userId: a.user_id, hallId: a.hall_id, sessionId }))
  const hallIds = allocations.map((a: any) => a.hall_id)
  const userIds = allocations.map((a: any) => a.user_id)

  const validation = validateAllocation(sessionId, entries, hallIds, userIds)
  if (!validation.isValid) return { success: false, validation }

  // BUG 4 fix: Wrap confirmation in an atomic transaction
  try {
    await db.runTransaction(async () => {
      await commitToHistory(
        sessionId,
        session.rotation_step,
        allocations.map((a: any) => ({ userId: a.user_id, hallId: a.hall_id, isAutoGenerated: !a.is_manually_edited }))
      )
      db.run("UPDATE exam_sessions SET status='confirmed', updated_at=datetime('now') WHERE id=?", [sessionId])
    })
    writeAuditLog(null, "CONFIRM_ALLOCATION", `Session ${sessionId} confirmed`, { sessionId, count: entries.length })
    return { success: true, validation }
  } catch (err: any) {
    return { success: false, error: err?.message || "Confirmation failed during transaction." }
  }
}

export function publishAllocation(sessionId: number) {
  const session = db.queryOne<any>("SELECT * FROM exam_sessions WHERE id = ?", [sessionId])
  if (!session) return { success: false, error: "Session not found." }
  if (session.status !== "confirmed") return { success: false, error: "Allocation must be confirmed before publishing." }
  db.run("UPDATE exam_sessions SET status='published', updated_at=datetime('now') WHERE id=?", [sessionId])
  // Roll up cycle status: if all sessions in cycle are published, mark cycle as published
  const unpublished = db.queryOne<any>(
    "SELECT COUNT(*) as c FROM exam_sessions WHERE cycle_id=? AND status != 'published'",
    [session.cycle_id]
  )
  if (!unpublished || unpublished.c === 0) {
    db.run("UPDATE exam_cycles SET status='published' WHERE id=?", [session.cycle_id])
  }
  writeAuditLog(null, "PUBLISH_ALLOCATION", `Session ${sessionId} published`, { sessionId })

  // In-app notifications for assigned staff
  try {
    const allocations = db.query<any>(
      `SELECT a.user_id, h.hall_code, ec.name as cycle_name
       FROM allocations a
       JOIN halls h ON a.hall_id = h.id
       JOIN exam_sessions es ON a.session_id = es.id
       JOIN exam_cycles ec ON es.cycle_id = ec.id
       WHERE a.session_id = ?`,
      [sessionId]
    )
    const sessionLabel = `${session.exam_date} ${session.session_type}`
    for (const a of allocations) {
      db.run(
        "INSERT INTO notifications(user_id, title, message, session_id) VALUES(?,?,?,?)",
        [
          a.user_id,
          "New Exam Duty Published",
          `Your invigilation duty has been published for ${sessionLabel} — Hall ${a.hall_code} (${a.cycle_name}).`,
          sessionId
        ]
      )
    }
  } catch (e) {
    console.warn("[EIAS] Failed to create notifications in desktop:", e)
  }

  return { success: true }
}


export function getSessionAllocationFull(sessionId: number) {
  return db.query(
    `SELECT a.id, a.is_manually_edited, a.edit_reason,
            u.id as userId, u.staff_id, u.name as userName, u.designation,
            d.name as deptName, d.code as deptCode,
            h.id as hallId, h.hall_code, h.name as hallName,
            gh.hall_code as generatedHallCode
     FROM allocations a
     JOIN users u ON a.user_id = u.id
     JOIN halls h ON a.hall_id = h.id
     LEFT JOIN departments d ON u.department_id = d.id
     LEFT JOIN halls gh ON a.generated_hall_id = gh.id
     WHERE a.session_id = ?
     ORDER BY d.code, u.name`,
    [sessionId]
  )
}

export function getValidHallsFor(userId: number, sessionId: number) {
  const occupied = db.query<any>("SELECT hall_id FROM allocations WHERE session_id = ?", [sessionId]).map((r: any) => r.hall_id)
  // BUG 5 fix: Session hall pool only
  const poolRows = db.query<any>(
    `SELECT DISTINCT h.id, h.sort_order 
     FROM allocations a
     JOIN halls h ON h.id = COALESCE(a.generated_hall_id, a.hall_id)
     WHERE a.session_id = ?
     ORDER BY h.sort_order, h.id`,
    [sessionId]
  )
  let sessionHalls = poolRows.map((r: any) => r.id)
  if (sessionHalls.length === 0) {
    sessionHalls = db.query<any>("SELECT id FROM halls WHERE is_active = 1 ORDER BY sort_order, id").map((h: any) => h.id)
  }
  return getValidHallsForStaff(userId, sessionId, sessionHalls, occupied)
}

export async function removeAllocationEntry(sessionId: number, userId: number) {
  const session = db.queryOne<any>("SELECT status FROM exam_sessions WHERE id = ?", [sessionId])
  if (!session) return { success: false, error: "Session not found." }
  if (session.status === "published") {
    return { success: false, error: "Cannot remove allocations from a published session. Reopen it first." }
  }
  const existing = db.queryOne<any>(
    "SELECT id FROM allocations WHERE session_id = ? AND user_id = ?",
    [sessionId, userId]
  )
  if (!existing) return { success: false, error: "Allocation entry not found." }
  db.run("DELETE FROM allocations WHERE session_id = ? AND user_id = ?", [sessionId, userId])
  writeAuditLog(null, "REMOVE_ALLOCATION", `Removed allocation for session ${sessionId}, user ${userId}`, { sessionId, userId })
  return { success: true }
}

export function getStaffDutyHistory(userId: number) {
  return db.query(
    `SELECT es.exam_date, es.session_type, es.reporting_time, es.exam_start, es.exam_end,
            h.id as hallId, h.hall_code, h.name as hallName,
            ec.name as cycleName, ec.academic_year,
            a.is_manually_edited
     FROM allocations a
     JOIN exam_sessions es ON a.session_id = es.id
     JOIN halls h ON a.hall_id = h.id
     JOIN exam_cycles ec ON es.cycle_id = ec.id
     WHERE a.user_id = ? AND es.status = 'published'
     ORDER BY es.exam_date DESC, es.session_type ASC`,
    [userId]
  )
}