import { describe, it, expect, beforeAll, beforeEach } from "vitest"
import { initDatabase, db } from "../db/database"
import { generateAllocation, commitToHistory } from "./rotation.engine"
import { validateAllocation, validateSingleEdit } from "./validation.engine"
import { getOrCreateAllocation, editAllocationEntry, confirmAllocation } from "./allocation.service"

// ??? Pure rotation logic (no DB needed) ??????????????????????????????????????

function circularNext(hallIds: number[], lastHallId: number): number {
  const idx = hallIds.indexOf(lastHallId)
  if (idx === -1) return hallIds[0]
  return hallIds[(idx + 1) % hallIds.length]
}

function generateFirstAllocation(userIds: number[], hallIds: number[]) {
  return userIds.map((userId, i) => ({ userId, hallId: hallIds[i % hallIds.length], isAutoGenerated: true }))
}

function generateRotation(
  userIds: number[],
  hallIds: number[],
  lastAssignments: Map<number, number>
): Map<number, number> {
  const result = new Map<number, number>()
  const used = new Set<number>()
  for (const userId of userIds) {
    const last = lastAssignments.get(userId)
    let candidate: number
    if (last !== undefined) {
      const idx = hallIds.indexOf(last)
      let found = false
      for (let attempt = 1; attempt <= hallIds.length; attempt++) {
        const c = hallIds[(idx + attempt) % hallIds.length]
        if (!used.has(c)) { candidate = c; found = true; break }
      }
      if (!found) candidate = hallIds.find(h => !used.has(h)) ?? hallIds[0]
    } else {
      candidate = hallIds.find(h => !used.has(h)) ?? hallIds[userIds.indexOf(userId) % hallIds.length]
    }
    result.set(userId, candidate!)
    used.add(candidate!)
  }
  return result
}

// ??? Validation rule helpers (pure logic) ????????????????????????????????????

function checkR2(entries: { userId: number; hallId: number }[]): boolean {
  const counts = new Map<number, number>()
  for (const e of entries) counts.set(e.hallId, (counts.get(e.hallId) ?? 0) + 1)
  return [...counts.values()].some(c => c > 1)
}

function checkR3(entries: { userId: number; hallId: number }[]): boolean {
  const counts = new Map<number, number>()
  for (const e of entries) counts.set(e.userId, (counts.get(e.userId) ?? 0) + 1)
  return [...counts.values()].some(c => c > 1)
}

function checkR7(staffCount: number, hallCount: number): boolean {
  return staffCount !== hallCount
}

function checkR1(userId: number, hallId: number, recentHalls: number[]): boolean {
  return recentHalls.includes(hallId)
}

function checkR5(isActive: boolean): boolean { return !isActive }
function checkR6(isActive: boolean): boolean { return !isActive }

// ??? TESTS ???????????????????????????????????????????????????????????????????

const halls = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
const staff = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

describe("Rotation Engine ? Core Algorithm", () => {
  describe("circularNext()", () => {
    it("returns next hall in sequence", () => {
      expect(circularNext(halls, 1)).toBe(2)
      expect(circularNext(halls, 5)).toBe(6)
      expect(circularNext(halls, 9)).toBe(10)
    })
    it("wraps around from last to first hall (H010 -> H001)", () => {
      expect(circularNext(halls, 10)).toBe(1)
    })
    it("returns first hall if lastHall not in current pool", () => {
      expect(circularNext(halls, 99)).toBe(1)
    })
  })

  describe("generateFirstAllocation()", () => {
    it("assigns halls in positional order for first session", () => {
      const result = generateFirstAllocation([101, 102, 103], [1, 2, 3])
      expect(result[0]).toEqual({ userId: 101, hallId: 1, isAutoGenerated: true })
      expect(result[1]).toEqual({ userId: 102, hallId: 2, isAutoGenerated: true })
      expect(result[2]).toEqual({ userId: 103, hallId: 3, isAutoGenerated: true })
    })
    it("uses modulo wrapping when more staff than halls", () => {
      const result = generateFirstAllocation([101, 102, 103, 104], [1, 2, 3])
      expect(result[3].hallId).toBe(1)
    })
  })

  describe("Multi-session rotation", () => {
    it("Each staff moves +1 hall per session", () => {
      const last = new Map(staff.map((s, i) => [s, halls[i]]))
      const s2 = generateRotation(staff, halls, last)
      expect(s2.get(101)).toBe(2)
      expect(s2.get(102)).toBe(3)
      expect(s2.get(110)).toBe(1) // wraps
    })

    it("No two staff share the same hall in any session", () => {
      const last = new Map(staff.map((s, i) => [s, halls[i]]))
      const s2 = generateRotation(staff, halls, last)
      const assigned = [...s2.values()]
      expect(new Set(assigned).size).toBe(assigned.length)
    })

    it("After N sessions (= hall count), each staff visits all halls exactly once", () => {
      let lastMap = new Map(staff.map((s, i) => [s, halls[i]]))
      const allSessions: Map<number, number>[] = [new Map(staff.map((s, i) => [s, halls[i]]))]
      for (let i = 2; i <= 10; i++) {
        const next = generateRotation(staff, halls, lastMap)
        allSessions.push(next)
        lastMap = next
      }
      const hallsFor101 = allSessions.map(s => s.get(101)!)
      expect(new Set(hallsFor101).size).toBe(10)
      expect([...new Set(hallsFor101)].sort((a, b) => a - b)).toEqual([1,2,3,4,5,6,7,8,9,10])
    })

    it("Session 11 restarts cycle (H010 -> H001)", () => {
      let lastMap = new Map(staff.map((s, i) => [s, halls[i]]))
      for (let i = 2; i <= 10; i++) lastMap = generateRotation(staff, halls, lastMap)
      expect(lastMap.get(101)).toBe(10)
      const s11 = generateRotation(staff, halls, lastMap)
      expect(s11.get(101)).toBe(1)
    })

    it("Handles staff whose last hall is no longer in pool", () => {
      const reducedHalls = [1, 2, 3, 4, 5] // hall 6 removed
      const lastMap = new Map([[101, 6]]) // staff 101 was in hall 6 (now gone)
      const result = generateRotation([101], reducedHalls, lastMap)
      expect(reducedHalls).toContain(result.get(101))
    })
  })
})

describe("Validation Rules ? Pure Logic", () => {
  describe("R1 ? Duplicate hall in rotation cycle", () => {
    it("BLOCKS when hall was used in last N sessions (still in cycle)", () => {
      expect(checkR1(101, 3, [1, 2, 3, 4, 5])).toBe(true)
    })
    it("ALLOWS hall used in a previous cycle (beyond window)", () => {
      expect(checkR1(101, 7, [1, 2, 3, 4, 5])).toBe(false)
    })
    it("ALLOWS brand new hall never used before", () => {
      expect(checkR1(101, 9, [])).toBe(false)
    })
  })

  describe("R2 ? Hall duplication in session", () => {
    it("BLOCKS when two staff share same hall", () => {
      expect(checkR2([{ userId: 101, hallId: 5 }, { userId: 102, hallId: 5 }])).toBe(true)
    })
    it("PASSES when all halls are unique", () => {
      expect(checkR2([{ userId: 101, hallId: 5 }, { userId: 102, hallId: 6 }])).toBe(false)
    })
    it("BLOCKS when 3 staff share same hall", () => {
      expect(checkR2([
        { userId: 101, hallId: 1 }, { userId: 102, hallId: 1 }, { userId: 103, hallId: 1 }
      ])).toBe(true)
    })
  })

  describe("R3 ? Staff duplication in session", () => {
    it("BLOCKS when same staff appears twice", () => {
      expect(checkR3([{ userId: 101, hallId: 1 }, { userId: 101, hallId: 2 }])).toBe(true)
    })
    it("PASSES when all staff IDs are unique", () => {
      expect(checkR3([{ userId: 101, hallId: 1 }, { userId: 102, hallId: 2 }])).toBe(false)
    })
  })

  describe("R5 ? Staff availability", () => {
    it("BLOCKS inactive staff", () => {
      expect(checkR5(false)).toBe(true)
    })
    it("PASSES active staff", () => {
      expect(checkR5(true)).toBe(false)
    })
  })

  describe("R6 ? Hall availability", () => {
    it("BLOCKS inactive hall", () => {
      expect(checkR6(false)).toBe(true)
    })
    it("PASSES active hall", () => {
      expect(checkR6(true)).toBe(false)
    })
  })

  describe("R7 ? Count match (staff = halls)", () => {
    it("BLOCKS when staff count != hall count", () => {
      expect(checkR7(8, 10)).toBe(true)
      expect(checkR7(12, 10)).toBe(true)
    })
    it("PASSES when counts are equal", () => {
      expect(checkR7(10, 10)).toBe(false)
      expect(checkR7(1, 1)).toBe(false)
    })
  })
})

// ??? INTEGRATION TESTS ? DATABASE & SERVICE FLOW (T1?T12) ???????????????????

describe("Integration Tests ? Database & Service Flow (T1?T12)", () => {
  beforeAll(async () => {
    await initDatabase({ inMemory: true })
  })

  beforeEach(() => {
    db.run("DELETE FROM rotation_history")
    db.run("DELETE FROM allocations")
    db.run("DELETE FROM exam_sessions")
    db.run("DELETE FROM exam_cycles")
    db.run("DELETE FROM halls")
    db.run("DELETE FROM users WHERE role='staff'")
    db.run("DELETE FROM departments")

    // Seed test master data
    db.run("INSERT INTO departments(id, code, name) VALUES(1, 'CSE', 'Computer Science')")
    for (let i = 1; i <= 10; i++) {
      const code = `H${String(i).padStart(3, "0")}`
      db.run("INSERT INTO halls(id, hall_code, name, capacity, sort_order, is_active) VALUES(?,?,?,?,?,1)", [
        i, code, `Hall ${i}`, 40, i
      ])
      const staffCode = `ST${String(i).padStart(3, "0")}`
      db.run("INSERT INTO users(id, staff_id, name, designation, role, department_id, is_active) VALUES(?,?,?,?,?,?,1)", [
        i, staffCode, `Staff ${i}`, "Assistant Professor", "staff", 1
      ])
    }

    // Default test cycle and sessions
    db.run("INSERT INTO exam_cycles(id, name, academic_year, status) VALUES(1, 'Cycle 1', '2026-27', 'draft')")
    db.run("INSERT INTO exam_cycles(id, name, academic_year, status) VALUES(2, 'Cycle 2', '2026-27', 'draft')")
    db.run("INSERT INTO exam_sessions(id, cycle_id, exam_date, session_type, rotation_step, status) VALUES(1, 1, '2026-11-01', 'FN', 1, 'pending')")
    db.run("INSERT INTO exam_sessions(id, cycle_id, exam_date, session_type, rotation_step, status) VALUES(2, 1, '2026-11-01', 'AN', 2, 'pending')")
    db.run("INSERT INTO exam_sessions(id, cycle_id, exam_date, session_type, rotation_step, status) VALUES(3, 1, '2026-11-02', 'FN', 3, 'pending')")
    db.run("INSERT INTO exam_sessions(id, cycle_id, exam_date, session_type, rotation_step, status) VALUES(4, 1, '2026-11-02', 'AN', 4, 'pending')")
    db.run("INSERT INTO exam_sessions(id, cycle_id, exam_date, session_type, rotation_step, status) VALUES(5, 1, '2026-11-03', 'FN', 5, 'pending')")
    db.run("INSERT INTO exam_sessions(id, cycle_id, exam_date, session_type, rotation_step, status) VALUES(6, 2, '2026-12-01', 'FN', 1, 'pending')")
    db.run("INSERT INTO exam_sessions(id, cycle_id, exam_date, session_type, rotation_step, status) VALUES(7, 2, '2026-12-01', 'AN', 2, 'pending')")
  })

  it("T1 ? New staff after existing history: new staff is treated as first-time participant", async () => {
    // Staff 1 already has finalized history in hall 1
    db.run(
      "INSERT INTO rotation_history(user_id, session_id, hall_id, rotation_step, global_order, recorded_at) VALUES(1, 1, 1, 1, 1, '2026-11-01 10:00:00')"
    )

    // Staff 2 has NO history. Both are selected for Session 2 with halls [1, 2]
    const result = await generateAllocation(2, [1, 2], [1, 2])

    const staff1Alloc = result.find(r => r.userId === 1)
    const staff2Alloc = result.find(r => r.userId === 2)

    // Staff 1 rotates from 1 -> 2
    expect(staff1Alloc?.hallId).toBe(2)
    // Staff 2 has no history, gets first available unoccupied hall in pool -> 1
    expect(staff2Alloc?.hallId).toBe(1)
  })

  it("T2 ? Session pool smaller than global hall count: cycleLength matches session pool size", async () => {
    // 10 active halls exist globally, but Session 1 uses 6 halls [1, 2, 3, 4, 5, 6]
    const sessionHalls = [1, 2, 3, 4, 5, 6]
    const sessionStaff = [1, 2, 3, 4, 5, 6]

    const result = await generateAllocation(1, sessionStaff, sessionHalls)
    expect(result.length).toBe(6)

    const entries = result.map(r => ({ ...r, sessionId: 1 }))
    const validation = validateAllocation(1, entries, sessionHalls, sessionStaff)
    expect(validation.isValid).toBe(true)
  })

  it("T3 ? Cycle reset ordering: latest assignment is determined chronologically across cycles", async () => {
    // Cycle 1: Session 5, step 5, global_order 5, hall 5
    db.run(
      "INSERT INTO rotation_history(user_id, session_id, hall_id, rotation_step, global_order, recorded_at) VALUES(1, 5, 5, 5, 5, '2026-10-01 10:00:00')"
    )
    // Cycle 2: Session 7, step 2, global_order 6, hall 2
    db.run(
      "INSERT INTO rotation_history(user_id, session_id, hall_id, rotation_step, global_order, recorded_at) VALUES(1, 7, 2, 2, 6, '2026-11-01 10:00:00')"
    )

    // Generate next session for Staff 1 with halls [1, 2, 3, 4, 5] (matching 5 staff)
    const result = await generateAllocation(1, [1, 2, 3, 4, 5], [1, 2, 3, 4, 5])
    const staff1 = result.find(r => r.userId === 1)
    // Should rotate from Hall 2 (latest in Cycle 2) -> Hall 3, NOT from Hall 5
    expect(staff1?.hallId).toBe(3)
  })

  it("T4 ? Cross-cycle latest history: Cycle 2 step 1 is newer than Cycle 1 step 5", async () => {
    // Cycle 1 Session 5 (step 5, global_order 5, hall 5)
    db.run(
      "INSERT INTO rotation_history(user_id, session_id, hall_id, rotation_step, global_order, recorded_at) VALUES(1, 5, 5, 5, 5, '2026-10-15 10:00:00')"
    )
    // Cycle 2 Session 6 (step 1, global_order 6, hall 1)
    db.run(
      "INSERT INTO rotation_history(user_id, session_id, hall_id, rotation_step, global_order, recorded_at) VALUES(1, 6, 1, 1, 6, '2026-11-01 10:00:00')"
    )

    const result = await generateAllocation(1, [1, 2, 3, 4, 5], [1, 2, 3, 4, 5])
    const staff1 = result.find(r => r.userId === 1)
    // Next hall should be 1 + 1 = 2, proving Cycle 2 step 1 is recognized as newer than step 5
    expect(staff1?.hallId).toBe(2)
  })

  it("T5 ? R1 current-cycle window uses session pool length instead of global count", async () => {
    // Session pool has 3 halls [1, 2, 3]. Staff 1 was in Hall 1 in previous session
    db.run(
      "INSERT INTO rotation_history(user_id, session_id, hall_id, rotation_step, global_order, recorded_at) VALUES(1, 1, 1, 1, 1, '2026-11-01 10:00:00')"
    )

    const entries = [{ userId: 1, hallId: 1, sessionId: 2 }]
    const validation = validateAllocation(2, entries, [1, 2, 3], [1])
    // Repeating Hall 1 within 3-hall cycle must trigger R1
    expect(validation.isValid).toBe(false)
    expect(validation.blockingErrors.some(e => e.rule === "R1")).toBe(true)
  })

  it("T6 ? Edit outside session pool is rejected", async () => {
    // Session 1 has pool [1, 2], allocated to Staff [1, 2]
    await getOrCreateAllocation(1, [1, 2], [1, 2])

    // Try to edit Staff 1's allocation to Hall 9 (active hall, but outside Session 1's pool [1, 2])
    const res = editAllocationEntry(1, 1, 9)
    expect(res.success).toBe(false)
    expect(res.error?.rule).toBe("SESSION_POOL")
  })

it("T7 ? Edited hall becomes future baseline", async () => {
    // Session 1: staff [1, 2], halls [1, 2]
    await getOrCreateAllocation(1, [1, 2], [1, 2])

    // Admin swaps their halls: delete and re-insert to avoid transient UNIQUE collisions
    db.run("DELETE FROM allocations WHERE session_id = 1")
    db.run("INSERT INTO allocations(session_id, user_id, hall_id, is_manually_edited, edit_reason, generated_hall_id) VALUES(1, 1, 2, 1, 'Swapped', 1)")
    db.run("INSERT INTO allocations(session_id, user_id, hall_id, is_manually_edited, edit_reason, generated_hall_id) VALUES(1, 2, 1, 1, 'Swapped', 2)")

    // Confirm Session 1
    const confRes = await confirmAllocation(1)
    expect(confRes.success).toBe(true)

    // Verify history recorded the edited hall (Hall 2 for Staff 1)
    const hist1 = db.queryOne<any>("SELECT hall_id FROM rotation_history WHERE session_id = 1 AND user_id = 1")
    expect(hist1.hall_id).toBe(2)
    const hist2 = db.queryOne<any>("SELECT hall_id FROM rotation_history WHERE session_id = 1 AND user_id = 2")
    expect(hist2.hall_id).toBe(1)

    // In Session 2 with halls [1, 2]: Staff 1 rotates from Hall 2 -> Hall 1 (or next in pool)
    const s2Res = await generateAllocation(2, [1, 2], [1, 2])
    const staff1 = s2Res.find(r => r.userId === 1)
    const staff2 = s2Res.find(r => r.userId === 2)
    // Staff 1: was edited to 2 -> next is 1
    expect(staff1?.hallId).toBe(1)
    // Staff 2: was edited to 1 -> next is 2
    expect(staff2?.hallId).toBe(2)
  })

  it("T8 ? Draft does not advance history until confirmed", async () => {
    // Generate draft for Session 1
    await getOrCreateAllocation(1, [1, 2], [1, 2])

    // rotation_history must remain empty
    const histCountBefore = db.queryOne<any>("SELECT COUNT(*) as c FROM rotation_history")
    expect(histCountBefore.c).toBe(0)

    // Confirm Session 1
    const confRes = await confirmAllocation(1)
    expect(confRes.success).toBe(true)

    // Now rotation_history has exactly 2 records
    const histCountAfter = db.queryOne<any>("SELECT COUNT(*) as c FROM rotation_history")
    expect(histCountAfter.c).toBe(2)
  })

  it("T9 ? Transaction rollback on failure leaves database untouched", async () => {
    await getOrCreateAllocation(1, [1, 2], [1, 2])

    // Attempt a transaction that modifies allocations then throws an error
    let threw = false
    try {
      await db.runTransaction(async () => {
        db.run("UPDATE allocations SET is_manually_edited=1 WHERE session_id=1 AND user_id=1")
        throw new Error("Controlled test failure")
      })
    } catch {
      threw = true
    }
    expect(threw).toBe(true)

    // Verify change was rolled back
    const alloc = db.queryOne<any>("SELECT is_manually_edited FROM allocations WHERE session_id=1 AND user_id=1")
    expect(alloc.is_manually_edited).toBe(0)
  })

  it("T10 ? Same-session uniqueness: duplicate staff or hall assignments cannot be confirmed", async () => {
    // Direct validation of duplicate assignment
    const dupHallEntries = [
      { userId: 1, hallId: 1, sessionId: 1 },
      { userId: 2, hallId: 1, sessionId: 1 }
    ]
    const valResult = validateAllocation(1, dupHallEntries, [1, 2], [1, 2])
    expect(valResult.isValid).toBe(false)
    expect(valResult.blockingErrors.some(e => e.rule === "R2")).toBe(true)

    // Duplicate staff validation
    const dupStaffEntries = [
      { userId: 1, hallId: 1, sessionId: 1 },
      { userId: 1, hallId: 2, sessionId: 1 }
    ]
    const valStaffResult = validateAllocation(1, dupStaffEntries, [1, 2], [1, 2])
    expect(valStaffResult.isValid).toBe(false)
    expect(valStaffResult.blockingErrors.some(e => e.rule === "R3")).toBe(true)
  })

  it("T11 ? Circular rotation wraps around from last hall to first", async () => {
    // Staff 1's previous hall was Hall 5 in a 5-hall pool
    db.run(
      "INSERT INTO rotation_history(user_id, session_id, hall_id, rotation_step, global_order, recorded_at) VALUES(1, 1, 5, 1, 1, '2026-11-01 10:00:00')"
    )

    const result = await generateAllocation(2, [1, 2, 3, 4, 5], [1, 2, 3, 4, 5])
    const staff1 = result.find(r => r.userId === 1)
    expect(staff1?.hallId).toBe(1)
  })

  it("T12 ? Staff-specific rotation: staff advances only when selected", async () => {
    const pool = [1, 2, 3]

    // Session 1: Staff [1, 2, 3]
    const s1 = await generateAllocation(1, [1, 2, 3], pool)
    await commitToHistory(1, 1, s1)
    expect(s1.find(r => r.userId === 1)?.hallId).toBe(1)
    expect(s1.find(r => r.userId === 2)?.hallId).toBe(2)
    expect(s1.find(r => r.userId === 3)?.hallId).toBe(3)

    // Session 2: Staff [1, 3, 4] (Staff 2 is absent!)
    const s2 = await generateAllocation(2, [1, 3, 4], pool)
    await commitToHistory(2, 2, s2)
    // Staff 1: was 1 -> rotates to 2
    expect(s2.find(r => r.userId === 1)?.hallId).toBe(2)
    // Staff 3: was 3 -> rotates to 1
    expect(s2.find(r => r.userId === 3)?.hallId).toBe(1)
    // Staff 4: new -> takes unoccupied hall 3
    expect(s2.find(r => r.userId === 4)?.hallId).toBe(3)

    // Session 3: Staff [2, 3, 4] (Staff 2 returns!)
    const s3 = await generateAllocation(3, [2, 3, 4], pool)
    // Staff 2 was absent in Session 2, last hall was Hall 2.
    // In Session 3, Staff 2 must rotate from Hall 2 -> Hall 3!
    const staff2Alloc = s3.find(r => r.userId === 2)
    expect(staff2Alloc?.hallId).toBe(3)
  })
})