/**
 * ROTATION ENGINE
 * Core circular hall allocation logic.
 * History is tracked indefinitely — no cycle resets.
 * Edit-aware: if admin edited a session, that becomes the rotation baseline.
 */
import { db } from "../db/database"

export interface AllocationEntry {
  userId: number
  hallId: number
  isAutoGenerated: boolean
}

export async function generateAllocation(
  sessionId: number,
  userIds: number[],
  hallIds: number[]
): Promise<AllocationEntry[]> {
  if (userIds.length !== hallIds.length) {
    throw new Error(`Staff count (${userIds.length}) must equal hall count (${hallIds.length})`)
  }

  const histCount = db.queryOne<any>("SELECT COUNT(*) as c FROM rotation_history")
  const isFirst = (histCount?.c ?? 0) === 0

  if (isFirst) return generateFirstAllocation(userIds, hallIds)

  const results: AllocationEntry[] = []
  const assignedHalls = new Set<number>()

  for (const userId of userIds) {
    const nextHallId = await computeNextHall(userId, hallIds, assignedHalls)
    results.push({ userId, hallId: nextHallId, isAutoGenerated: true })
    assignedHalls.add(nextHallId)
  }
  return results
}

export function generateFirstAllocation(userIds: number[], hallIds: number[]): AllocationEntry[] {
  return userIds.map((userId, i) => ({
    userId,
    hallId: hallIds[i % hallIds.length],
    isAutoGenerated: true
  }))
}

async function computeNextHall(
  userId: number,
  hallIds: number[],
  alreadyAssigned: Set<number>
): Promise<number> {
  const lastRecord = db.queryOne<any>(
    "SELECT hall_id FROM rotation_history WHERE user_id = ? ORDER BY rotation_step DESC LIMIT 1",
    [userId]
  )

  if (!lastRecord) {
    // No history: find first unoccupied hall in pool
    return hallIds.find(h => !alreadyAssigned.has(h)) ?? hallIds[0]
  }

  const lastHallIndex = hallIds.indexOf(lastRecord.hall_id)
  if (lastHallIndex === -1) {
    // Last hall not in current pool — find first unused hall
    return (
      hallIds.find(h => !alreadyAssigned.has(h) && !isUsedInCurrentCycle(userId, h, hallIds.length)) ??
      hallIds.find(h => !alreadyAssigned.has(h)) ??
      hallIds[0]
    )
  }

  // Try circular +1, skip if already taken in this session
  for (let attempt = 1; attempt <= hallIds.length; attempt++) {
    const candidate = hallIds[(lastHallIndex + attempt) % hallIds.length]
    if (!alreadyAssigned.has(candidate)) return candidate
  }
  return hallIds[0]
}

function isUsedInCurrentCycle(userId: number, hallId: number, cycleLength: number): boolean {
  const recentRows = db.query<any>(
    "SELECT hall_id FROM rotation_history WHERE user_id = ? ORDER BY rotation_step DESC LIMIT ?",
    [userId, cycleLength]
  )
  return recentRows.some(r => r.hall_id === hallId)
}

export async function commitToHistory(
  sessionId: number,
  rotationStep: number,
  entries: AllocationEntry[]
): Promise<void> {
  for (const e of entries) {
    db.run(
      `INSERT INTO rotation_history(user_id, session_id, hall_id, rotation_step)
       VALUES(?,?,?,?)
       ON CONFLICT(user_id, session_id) DO UPDATE SET hall_id=excluded.hall_id, rotation_step=excluded.rotation_step`,
      [e.userId, sessionId, e.hallId, rotationStep]
    )
  }
}

export function getStaffHallHistory(userId: number): any[] {
  return db.query(
    `SELECT rh.hall_id as hallId, rh.session_id as sessionId, rh.rotation_step as rotationStep,
            es.exam_date as examDate, es.session_type as sessionType
     FROM rotation_history rh
     JOIN exam_sessions es ON rh.session_id = es.id
     WHERE rh.user_id = ?
     ORDER BY rh.rotation_step ASC`,
    [userId]
  )
}
