/**
 * ROTATION ENGINE
 * Core circular hall allocation logic.
 * History is tracked indefinitely ? no cycle resets.
 * Edit-aware: if admin edited a session, that becomes the rotation baseline.
 * Individual-aware: each staff member maintains their own rotation state.
 */
import { db } from "../db/database"

export interface AllocationEntry {
  userId: number
  hallId: number
  isAutoGenerated: boolean
}

export async function generateAllocation(
  sessionId: number,
  userIds: number[],
  hallIds: number[]
): Promise<AllocationEntry[]> {
  if (userIds.length !== hallIds.length) {
    throw new Error(`Staff count (${userIds.length}) must equal hall count (${hallIds.length})`)
  }

  // Check history per staff individually (BUG 1 fix: no global first-allocation check)
  const staffWithHistory: number[] = []
  const staffWithoutHistory: number[] = []

  for (const userId of userIds) {
    const hist = db.queryOne<any>(
      "SELECT id FROM rotation_history WHERE user_id = ? LIMIT 1",
      [userId]
    )
    if (hist) {
      staffWithHistory.push(userId)
    } else {
      staffWithoutHistory.push(userId)
    }
  }

  const assignedMap = new Map<number, number>()
  const assignedHalls = new Set<number>()

  // 1. Allocate staff with history first so their circular progression is respected
  for (const userId of staffWithHistory) {
    const nextHallId = await computeNextHall(userId, hallIds, assignedHalls)
    assignedMap.set(userId, nextHallId)
    assignedHalls.add(nextHallId)
  }

  // 2. Allocate new staff without history to first available unoccupied halls
  for (const userId of staffWithoutHistory) {
    const nextHallId = await computeNextHall(userId, hallIds, assignedHalls)
    assignedMap.set(userId, nextHallId)
    assignedHalls.add(nextHallId)
  }

  // Preserve original userIds order in returned entries
  return userIds.map(userId => ({
    userId,
    hallId: assignedMap.get(userId)!,
    isAutoGenerated: true
  }))
}

export function generateFirstAllocation(userIds: number[], hallIds: number[]): AllocationEntry[] {
  return userIds.map((userId, i) => ({
    userId,
    hallId: hallIds[i % hallIds.length],
    isAutoGenerated: true
  }))
}

async function computeNextHall(
  userId: number,
  hallIds: number[],
  alreadyAssigned: Set<number>
): Promise<number> {
  // BUG 3 fix: Order chronologically by global_order DESC, recorded_at DESC, id DESC
  const lastRecord = db.queryOne<any>(
    "SELECT hall_id FROM rotation_history WHERE user_id = ? ORDER BY COALESCE(global_order, 0) DESC, datetime(recorded_at) DESC, id DESC LIMIT 1",
    [userId]
  )

  if (!lastRecord) {
    // No history: find first unoccupied hall in current session pool
    const firstFree = hallIds.find(h => !alreadyAssigned.has(h))
    if (firstFree !== undefined) return firstFree
    return hallIds[0]
  }

  const lastHallIndex = hallIds.indexOf(lastRecord.hall_id)
  if (lastHallIndex === -1) {
    // Last hall not in current pool ? fallback to first unused hall in pool that wasn't used in current cycle
    const cycleLength = hallIds.length
    const candidate =
      hallIds.find(h => !alreadyAssigned.has(h) && !isUsedInCurrentCycle(userId, h, cycleLength)) ??
      hallIds.find(h => !alreadyAssigned.has(h)) ??
      hallIds[0]
    return candidate
  }

  // Try circular +1, +2, ..., skip if already taken in this session
  for (let attempt = 1; attempt <= hallIds.length; attempt++) {
    const candidate = hallIds[(lastHallIndex + attempt) % hallIds.length]
    if (!alreadyAssigned.has(candidate)) return candidate
  }
  return hallIds[0]
}

function isUsedInCurrentCycle(userId: number, hallId: number, cycleLength: number): boolean {
  // BUG 6 fix: Order chronologically by global_order DESC, recorded_at DESC, id DESC
  const recentRows = db.query<any>(
    "SELECT hall_id FROM rotation_history WHERE user_id = ? ORDER BY COALESCE(global_order, 0) DESC, datetime(recorded_at) DESC, id DESC LIMIT ?",
    [userId, cycleLength]
  )
  return recentRows.some(r => r.hall_id === hallId)
}

export async function commitToHistory(
  sessionId: number,
  rotationStep: number,
  entries: AllocationEntry[]
): Promise<void> {
  const maxRow = db.queryOne<{ max_order: number | null }>(
    "SELECT MAX(global_order) as max_order FROM rotation_history"
  )
  let nextGlobalOrder = (maxRow?.max_order ?? 0) + 1

  for (const e of entries) {
    const existing = db.queryOne<{ id: number; global_order: number }>(
      "SELECT id, global_order FROM rotation_history WHERE user_id = ? AND session_id = ?",
      [e.userId, sessionId]
    )

    if (existing) {
      db.run(
        `UPDATE rotation_history 
         SET hall_id = ?, rotation_step = ?, recorded_at = datetime('now')
         WHERE id = ?`,
        [e.hallId, rotationStep, existing.id]
      )
    } else {
      db.run(
        `INSERT INTO rotation_history(user_id, session_id, hall_id, rotation_step, global_order, recorded_at)
         VALUES(?,?,?,?,?,datetime('now'))`,
        [e.userId, sessionId, e.hallId, rotationStep, nextGlobalOrder++]
      )
    }
  }
}

export function getStaffHallHistory(userId: number): any[] {
  return db.query(
    `SELECT rh.hall_id as hallId, rh.session_id as sessionId, rh.rotation_step as rotationStep,
            rh.global_order as globalOrder, es.exam_date as examDate, es.session_type as sessionType
     FROM rotation_history rh
     JOIN exam_sessions es ON rh.session_id = es.id
     WHERE rh.user_id = ?
     ORDER BY COALESCE(rh.global_order, 0) ASC, datetime(rh.recorded_at) ASC, rh.id ASC`,
    [userId]
  )
}