export interface Department {
  id: number;
  code: string;
  name: string;
  is_active: boolean;
  is_deleted?: boolean;
  created_at: string;
}

export interface Staff {
  id: number;
  staff_id: string;
  name: string;
  email?: string;
  designation?: string;
  role: "admin" | "staff";
  department_id?: number;
  department_name?: string;
  department_code?: string;
  is_active: boolean;
  is_deleted?: boolean;
  created_at: string;
}

export interface Hall {
  id: number;
  hall_code: string;
  name: string;
  capacity: number;
  block?: string;
  sort_order: number;
  is_active: boolean;
  is_deleted?: boolean;
  required_invigilators?: number;
}

export interface ExamCycle {
  id: number;
  name: string;
  academic_year: string;
  status: "draft" | "active" | "closed" | "published";
  created_at: string;
  updated_at?: string;
}

export interface ExamSession {
  id: number;
  cycle_id: number;
  exam_date: string;
  session_type: "FN" | "AN";
  rotation_step: number;
  reporting_time?: string;
  exam_start?: string;
  exam_end?: string;
  status: "pending" | "draft" | "confirmed" | "published";
  created_at: string;
  updated_at?: string;
}

export interface Allocation {
  id: number;
  session_id: number;
  user_id: number;
  hall_id: number;
  is_manually_edited: boolean;
  edit_reason?: string;
  generated_hall_id?: number;
  user?: Staff;
  hall?: Hall;
  session?: ExamSession;
  is_deleted?: boolean;
}

export interface RotationHistory {
  id: number;
  user_id: number;
  session_id: number;
  hall_id: number;
  rotation_step: number;
  recorded_at: string;
  global_order?: number;
  hall?: Hall;
  session?: ExamSession;
}

export interface ValidationError {
  rule: string;
  message: string;
  userId?: number;
  hallId?: number;
}

export interface ValidationResult {
  isValid: boolean;
  blockingErrors: ValidationError[];
  warnings: string[];
}

export interface AllocationDraft {
  sessionId: number;
  entries: Array<{ userId: number; hallId: number; isEdited: boolean; editReason?: string }>;
}

export interface AllocationEntry {
  userId: number;
  hallId: number;
  isAutoGenerated: boolean;
}

export interface AppSettings {
  "college.name": string;
  "college.short_name": string;
  "session.fn_reporting_time": string;
  "session.fn_start_time": string;
  "session.fn_end_time": string;
  "session.an_reporting_time": string;
  "session.an_start_time": string;
  "session.an_end_time": string;
  [key: string]: string;
}

export interface HallRequirement {
  hall: Hall;
  slotsNeeded: number;
}

export interface AllocationGenerationResult {
  success: boolean;
  allocations?: Array<{
    userId: number;
    hallId: number;
    role: "Senior Invigilator" | "Junior Invigilator" | "Relief Invigilator";
  }>;
  standbyStaff?: number[];
  nextRotationStep?: number;
  errorMessage?: string;
  totalSlotsNeeded?: number;
}

export interface ManualEditConflict {
  type: "double_booking" | "hall_taken" | "rotation_cycle";
  message: string;
  conflictingStaffId?: number;
  conflictingHallId?: number;
  conflictingSessionId?: number;
}